Week 4 Lecture 1

In [ ]:
#append to list:
a = [1,2,3]
print(a+[4])
print(a.append(4))

#remove last element
print(a.pop())

In [2]:
#Slicing

a = list(range(10))
print(a)

#Select slices
print(a[3:7])

#Modify sublists
a[3:5] = [-1:0]
print(a)


SyntaxError: invalid syntax (1069588601.py, line 10)

In [4]:
a = list(range(10))

#Enumerate
for pos, var in enumerate(a):
    print(pos,var)

0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9


In [ ]:
#dictionaries
a_dict = {}
b_dict = {'abc':1, 'def':2}

b_dict['abc'] = 3
print(b_dict)

print(b_dict['def'])

print(b_dict.get('g','NA'))

del b_dict['def']
print(b_dict)

In [ ]:
#Numpy

#np arrays vs lists: can only store elements of the same type in np arrays
a = np.array([1,2,3], dtype=np.float)
print(a)

print(a.dtype)
a = np.array([[1,2,3],[4,5,6],[7,8,9]])




In [8]:
import numpy as np

#np.zeros/ones((m,n))

#array of constants:

#identity matrix of that size
print(np.eye((4))) 

#array indexing and slicing
a = np.random.randint(1,10,size=(3,3))
print(a)

#slicing
print(a[:2,1:2])

#sub-arrays and modding:
b = a[:2,1:2]
a[:2,1:2] = [[-1],[-1]]
print(b)
print(a)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[6 4 6]
 [4 4 5]
 [1 7 9]]
[[4]
 [4]]
[[-1]
 [-1]]
[[ 6 -1  6]
 [ 4 -1  5]
 [ 1  7  9]]


In [10]:
#Array indexing:
a = np.arange(10)
print(a)
b = [0,5,6]
print(a[b])

print(a[:-1])


#Boolean indexing:
b = a > 4
print(a[b])

[0 1 2 3 4 5 6 7 8 9]
[0 5 6]
[0 1 2 3 4 5 6 7 8]
[5 6 7 8 9]


In [ ]:
#Reshaping arrays:

a = np.random.randint(1,10,size=(3,3))
print(a)
print(np.reshape(a,(9,1)))

#Transpose or arrays:
print(a.T)

#Stacking
b = np.random.randint()


In [ ]:
#Math ops:
c = np.array([3,4,5])
print(a.dot(c))

In [ ]:
#BROADCASTING

#you're expanging the smaller array to a compatible shape so you can do the operation fast

a = np.array([1,2,3,4])
c = a * 2

temp = [2,2,2,2]

a = np.random.randint(0,10,size=(3,2))
print(a.shape)